[#2671] fix QR code appearance in dark mode
maykinmedia/django-two-factor-auth pull request #14
Opened 2023-02-13 15:05 UTC by pi-sigma

Fixes open-formulieren/open-forms#2671

* added `style` attribute to the `img` tag with the QR code to add white background

2023-02-13 15:29 UTC, pi-sigma commented
I changed the platform for GitHub actions to `ubuntu-20.04` because of test failures that resulted from a lack of support for certain Python versions (discussion of this issue [here](https://github.com/actions/setup-python/issues/543) and [here](https://github.com/actions/setup-python/issues/544). Not sure if this is the right approach.

2023-02-14 09:04 UTC, sergei-maertens requested changes

2023-02-14 09:04 UTC, sergei-maertens commented on two_factor/templates/two_factor/admin/setup.html
> +    <p><img class="centered-image" style="background-color: white" src="{{ QR_URL }}" alt="QR Code" /></p>
this needs to be fixed in the CSS, not with inline styles as Content-Security Policies will block this (inline styles are typically blocked)

2023-02-14 09:09 UTC, sergei-maertens requested changes

2023-02-14 09:09 UTC, sergei-maertens commented on .github/workflows/ci.yml
> +        uses: codecov/codecov-action@v1.5.2
wasn't there a v3 already? I think we use that in the open forms backend

2023-02-14 09:09 UTC, sergei-maertens commented on .github/workflows/ci.yml
>          django-version: ['2.2', '3.0', '3.1']
2.2 is end of life, so are 3.0 and 3.1. We should only support 3.2 (and 4.2 in a couple of weeks when it releases)

2023-02-14 09:09 UTC, sergei-maertens commented on tox.ini
> +    py{38,39,310,311}-djmaster-{normal,yubikey,custom_user}
this build matrix also needs updating for proper django 3.2+ env, take a look at https://github.com/maykinmedia/drf-polymorphic/blob/main/tox.ini#L3 for example

2023-02-14 09:09 UTC, sergei-maertens commented on tox.ini
> +    3.11: py311, mypy
doesn't need mypy afaik, I don't know what the mypy version targets

2023-02-15 14:18 UTC, sergei-maertens approved these changes

2023-02-16 17:10 UTC, sergei-maertens commented
decided against updating this fork and instead we'll tackle things in OF directly.

2023-02-16 17:10 UTC, closed without merging